/**
 * OpenEMR MySQL Sync Module
 * Syncs SSO user details → OpenEMR database (users, users_secure, gacl_aro, gacl_groups_aro_map)
 */
import mysql from 'mysql2/promise';
import { randomUUID } from 'crypto';

// OpenEMR ACL group IDs (from gacl_aro_groups)
const ROLE_GROUP_MAP: Record<string, number> = {
    admin: 11,
    clin: 12,
    doc: 13,
    front: 14,
    back: 15,
    breakglass: 16,
};

let pool: mysql.Pool;

export function initOpenEMRPool() {
    pool = mysql.createPool({
        host: process.env.OPENEMR_DB_HOST || 'openemr-db',
        port: parseInt(process.env.OPENEMR_DB_PORT || '3306'),
        user: process.env.OPENEMR_DB_USER || 'openemr',
        password: process.env.OPENEMR_DB_PASS || 'openemr',
        database: process.env.OPENEMR_DB_NAME || 'openemr',
        waitForConnections: true,
        connectionLimit: 5,
    });
    console.log('[OpenEMR-Sync] MySQL pool initialized');
}

/**
 * Get the facility name from OpenEMR by facility ID
 */
async function getFacilityName(facilityId: number): Promise<string> {
    if (!pool || facilityId <= 0) return '';
    try {
        const [rows] = await pool.query('SELECT name FROM facility WHERE id = ? LIMIT 1', [facilityId]) as any;
        return rows.length > 0 ? rows[0].name : '';
    } catch { return ''; }
}

/**
 * List all facilities from OpenEMR
 */
export async function listFacilities(): Promise<{ id: number; name: string }[]> {
    if (!pool) return [];
    const [rows] = await pool.query('SELECT id, name FROM facility WHERE inactive = 0 ORDER BY name ASC') as any;
    return rows.map((r: any) => ({ id: r.id, name: r.name }));
}

/**
 * Parse display name into first/last name
 */
function parseName(displayName: string): { fname: string; lname: string } {
    const parts = displayName.trim().split(/\s+/);
    if (parts.length === 1) return { fname: parts[0], lname: '' };
    const lname = parts.pop()!;
    return { fname: parts.join(' '), lname };
}

/**
 * Get the next available gacl_aro ID
 */
async function getNextAroId(): Promise<number> {
    const [rows] = await pool.query('SELECT MAX(id) as maxId FROM gacl_aro') as any;
    return (rows[0]?.maxId || 10) + 1;
}

/**
 * Standard SSO password hash for OpenEMR accounts.
 * Generated by PHP's password_hash('pass', PASSWORD_BCRYPT).
 * Since SSO is the real auth layer, OpenEMR uses this standard password
 * for auto-login form submission only.
 */
const OPENEMR_SSO_PASSWORD_HASH = '$2y$10$YQnEfbNz8F3fEgLRTfJEoOnXZH08BXfC3S87q0AA54KEdzrtXtTyG';

/**
 * Sync a user from SSO → OpenEMR
 * Creates or updates the user in:
 *   - `users` table (profile)
 *   - `users_secure` table (password — standard SSO password)
 *   - `gacl_aro` (ACL entry)
 *   - `gacl_groups_aro_map` (role group assignment)
 */
export async function syncUserToOpenEMR(
    username: string,
    displayName: string,
    email: string,
    _passwordHash: string, // kept for API compat but not used — we use standard SSO hash
    role: string,
    status: string = 'active',
    facilityId: number = 0,
): Promise<void> {
    if (!pool) { console.warn('[OpenEMR-Sync] Pool not initialized, skipping sync'); return; }

    const conn = await pool.getConnection();
    try {
        await conn.beginTransaction();

        const { fname, lname } = parseName(displayName);
        const isActive = status === 'active' ? 1 : 0;
        const authorized = ['admin', 'doc', 'clin'].includes(role) ? 1 : 0;
        const groupId = ROLE_GROUP_MAP[role] || ROLE_GROUP_MAP.front;

        // 1. Check if user exists in OpenEMR
        const [existingRows] = await conn.query(
            'SELECT id FROM users WHERE username = ? LIMIT 1',
            [username]
        ) as any;

        let userId: number;

        if (existingRows.length > 0) {
            userId = existingRows[0].id;

            // Update existing user profile
            await conn.query(
                `UPDATE users SET fname = ?, lname = ?, email = ?, active = ?, authorized = ?, facility_id = ? WHERE id = ?`,
                [fname, lname, email, isActive, authorized, facilityId, userId]
            );

            // Ensure UUID exists (OpenEMR requires it for login)
            const [uuidRows] = await conn.query('SELECT uuid FROM users WHERE id = ? AND uuid IS NOT NULL', [userId]) as any;
            if (uuidRows.length === 0) {
                const uuid = Buffer.from(randomUUID().replace(/-/g, ''), 'hex');
                await conn.query('UPDATE users SET uuid = ? WHERE id = ?', [uuid, userId]);
            }

            // Update password in users_secure
            await conn.query(
                `UPDATE users_secure SET password = ?, last_update_password = NOW() WHERE id = ?`,
                [OPENEMR_SSO_PASSWORD_HASH, userId]
            );

            console.log(`[OpenEMR-Sync] Updated user: ${username} (id=${userId})`);
        } else {
            // Insert new user into `users` with UUID
            const uuid = Buffer.from(randomUUID().replace(/-/g, ''), 'hex');
            const [insertResult] = await conn.query(
                `INSERT INTO users (username, password, uuid, fname, lname, email, authorized, active, calendar, facility_id)
                 VALUES (?, 'NoLongerUsed', ?, ?, ?, ?, ?, ?, 1, ?)`,
                [username, uuid, fname, lname, email, authorized, isActive, facilityId]
            ) as any;
            userId = insertResult.insertId;

            // Insert into `users_secure`
            await conn.query(
                `INSERT INTO users_secure (id, username, password, last_update_password)
                 VALUES (?, ?, ?, NOW())`,
                [userId, username, OPENEMR_SSO_PASSWORD_HASH]
            );

            console.log(`[OpenEMR-Sync] Created user: ${username} (id=${userId})`);
        }

        // 2. Sync ACL entry (gacl_aro)
        const [aroRows] = await conn.query(
            'SELECT id FROM gacl_aro WHERE section_value = ? AND value = ? LIMIT 1',
            ['users', username]
        ) as any;

        let aroId: number;
        if (aroRows.length > 0) {
            aroId = aroRows[0].id;
            // Update name
            await conn.query(
                'UPDATE gacl_aro SET name = ? WHERE id = ?',
                [displayName, aroId]
            );
        } else {
            aroId = await getNextAroId();
            await conn.query(
                'INSERT INTO gacl_aro (id, section_value, value, order_value, name, hidden) VALUES (?, ?, ?, ?, ?, 0)',
                [aroId, 'users', username, 10, displayName]
            );
        }

        // 3. Sync role group (gacl_groups_aro_map)
        // Remove existing group assignments
        await conn.query('DELETE FROM gacl_groups_aro_map WHERE aro_id = ?', [aroId]);
        // Assign to new group
        await conn.query(
            'INSERT INTO gacl_groups_aro_map (group_id, aro_id) VALUES (?, ?)',
            [groupId, aroId]
        );

        // 4. Ensure user is in the `groups` table (required by OpenEMR login)
        const [groupRows] = await conn.query(
            'SELECT id FROM `groups` WHERE `user` = ? LIMIT 1',
            [username]
        ) as any;
        if (groupRows.length === 0) {
            await conn.query(
                'INSERT INTO `groups` (`name`, `user`) VALUES (?, ?)',
                ['Default', username]
            );
        }

        await conn.commit();
        console.log(`[OpenEMR-Sync] Synced ${username} → group ${role} (gid=${groupId})`);
    } catch (err: any) {
        await conn.rollback();
        console.error(`[OpenEMR-Sync] Error syncing ${username}:`, err.message);
    } finally {
        conn.release();
    }
}

/**
 * Delete a user from OpenEMR
 */
export async function deleteOpenEMRUser(username: string): Promise<void> {
    if (!pool) return;

    const conn = await pool.getConnection();
    try {
        await conn.beginTransaction();

        // Get user ID
        const [rows] = await conn.query('SELECT id FROM users WHERE username = ? LIMIT 1', [username]) as any;
        if (rows.length > 0) {
            const userId = rows[0].id;
            await conn.query('DELETE FROM users_secure WHERE id = ?', [userId]);
            await conn.query('DELETE FROM users WHERE id = ?', [userId]);
        }

        // Remove ACL entries
        const [aroRows] = await conn.query(
            'SELECT id FROM gacl_aro WHERE section_value = ? AND value = ?',
            ['users', username]
        ) as any;
        if (aroRows.length > 0) {
            const aroId = aroRows[0].id;
            await conn.query('DELETE FROM gacl_groups_aro_map WHERE aro_id = ?', [aroId]);
            await conn.query('DELETE FROM gacl_aro WHERE id = ?', [aroId]);
        }

        await conn.commit();
        console.log(`[OpenEMR-Sync] Deleted user from OpenEMR: ${username}`);
    } catch (err: any) {
        await conn.rollback();
        console.error(`[OpenEMR-Sync] Error deleting ${username}:`, err.message);
    } finally {
        conn.release();
    }
}

/**
 * Sync on login — lightweight: ensure user exists and profile is up-to-date
 */
export async function syncOnLogin(
    username: string,
    displayName: string,
    email: string,
    passwordHash: string,
    role: string,
    facilityId: number = 0,
): Promise<void> {
    return syncUserToOpenEMR(username, displayName, email, passwordHash, role, 'active', facilityId);
}

// ===========================================================
// Appointment Sync: OpenEMR → Medplum FHIR
// ===========================================================

export interface OpenEMRAppointment {
    eid: number;
    catid: number;
    aid: string;
    pid: string;
    title: string;
    eventDate: string;
    startTime: string;
    endTime: string;
    duration: number;
    status: string;
    facility: number;
    notes: string;
}

const APPT_STATUS_MAP: Record<string, string> = {
    '-': 'booked', '#': 'booked',
    '>': 'arrived', '~': 'arrived', '@': 'arrived',
    'x': 'fulfilled', '?': 'noshow', '%': 'cancelled',
};

const APPT_SYSTEM_ID = 'https://medseal.io/openemr/appointment';

/**
 * Read all appointments from OpenEMR
 */
export async function readOpenEMRAppointments(): Promise<OpenEMRAppointment[]> {
    if (!pool) return [];
    const [rows] = await pool.query(
        `SELECT pc_eid, pc_catid, pc_aid, pc_pid, pc_title, pc_eventDate, pc_startTime, pc_endTime,
                pc_duration, pc_apptstatus, pc_facility, pc_hometext
         FROM openemr_postcalendar_events
         WHERE pc_pid > 0 AND pc_eventstatus = 1
         ORDER BY pc_eventDate, pc_startTime`
    ) as any;
    return rows.map((r: any) => ({
        eid: r.pc_eid,
        catid: r.pc_catid,
        aid: String(r.pc_aid || ''),
        pid: String(r.pc_pid || ''),
        title: r.pc_title || '',
        eventDate: r.pc_eventDate ? new Date(r.pc_eventDate).toISOString().split('T')[0] : '',
        startTime: r.pc_startTime || '00:00:00',
        endTime: r.pc_endTime || '00:00:00',
        duration: r.pc_duration || 0,
        status: r.pc_apptstatus || '-',
        facility: r.pc_facility || 0,
        notes: r.pc_hometext || '',
    }));
}

/**
 * Sync OpenEMR appointments → Medplum FHIR
 */
export async function syncAppointmentsToFHIR(
    medplumBase: string,
    token: string,
): Promise<{ created: number; updated: number; skipped: number; failed: number; total: number }> {
    const result = { created: 0, updated: 0, skipped: 0, failed: 0, total: 0 };

    // 1. Read OpenEMR appointments
    const appointments = await readOpenEMRAppointments();
    result.total = appointments.length;
    if (appointments.length === 0) return result;

    // 2. Build patient map (sequential FHIR ID assignment)
    const patientMap: Record<string, string> = {};
    let patUrl: string | null = `${medplumBase}/fhir/R4/Patient?_count=200`;
    let patPage = 0;
    while (patUrl && patPage < 50) {
        const res = await fetch(patUrl, { headers: { 'Authorization': `Bearer ${token}` } });
        if (!res.ok) break;
        const bundle: any = await res.json();
        (bundle.entry || []).forEach((e: any, i: number) => {
            patientMap[String(patPage * 200 + i + 1)] = e.resource.id;
        });
        const next = (bundle.link || []).find((l: any) => l.relation === 'next');
        patUrl = next ? next.url : null;
        patPage++;
    }

    // 3. Build practitioner map
    const practMap: Record<string, string> = {};
    let practUrl: string | null = `${medplumBase}/fhir/R4/Practitioner?_count=200`;
    let practPage = 0;
    while (practUrl && practPage < 10) {
        const res = await fetch(practUrl, { headers: { 'Authorization': `Bearer ${token}` } });
        if (!res.ok) break;
        const bundle: any = await res.json();
        (bundle.entry || []).forEach((e: any, i: number) => {
            practMap[String(practPage * 200 + i + 1)] = e.resource.id;
        });
        const next = (bundle.link || []).find((l: any) => l.relation === 'next');
        practUrl = next ? next.url : null;
        practPage++;
    }

    // 4. Index existing synced appointments
    const existingIndex: Record<string, string> = {};
    let idxUrl: string | null = `${medplumBase}/fhir/R4/Appointment?identifier=${encodeURIComponent(APPT_SYSTEM_ID + '|')}&_count=200`;
    let idxPage = 0;
    while (idxUrl && idxPage < 50) {
        const res = await fetch(idxUrl, { headers: { 'Authorization': `Bearer ${token}` } });
        if (!res.ok) break;
        const bundle: any = await res.json();
        for (const e of (bundle.entry || [])) {
            const eid = (e.resource.identifier || []).find((id: any) => id.system === APPT_SYSTEM_ID)?.value;
            if (eid) existingIndex[eid] = e.resource.id;
        }
        const next = (bundle.link || []).find((l: any) => l.relation === 'next');
        idxUrl = next ? next.url : null;
        idxPage++;
    }

    // 5. Sync each appointment
    for (const appt of appointments) {
        const fhirPatId = patientMap[appt.pid];
        if (!fhirPatId) { result.skipped++; continue; }

        const fhirStatus = APPT_STATUS_MAP[appt.status] || 'proposed';
        const participants: any[] = [
            { actor: { reference: `Patient/${fhirPatId}` }, status: 'accepted' },
        ];
        const fhirPractId = practMap[appt.aid];
        if (fhirPractId) {
            participants.push({ actor: { reference: `Practitioner/${fhirPractId}` }, status: 'accepted' });
        }

        const resource: any = {
            resourceType: 'Appointment',
            identifier: [{ system: APPT_SYSTEM_ID, value: String(appt.eid) }],
            status: fhirStatus,
            serviceType: [{ coding: [{ display: appt.title }], text: appt.title }],
            appointmentType: { coding: [{ display: appt.title }], text: appt.title },
            start: `${appt.eventDate}T${appt.startTime}+00:00`,
            end: `${appt.eventDate}T${appt.endTime}+00:00`,
            minutesDuration: appt.duration > 0 ? Math.round(appt.duration / 60) : 15,
            participant: participants,
        };

        const existingId = existingIndex[String(appt.eid)];
        try {
            if (existingId) {
                resource.id = existingId;
                const res = await fetch(`${medplumBase}/fhir/R4/Appointment/${existingId}`, {
                    method: 'PUT',
                    headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
                    body: JSON.stringify(resource),
                });
                res.ok ? result.updated++ : result.failed++;
            } else {
                const res = await fetch(`${medplumBase}/fhir/R4/Appointment`, {
                    method: 'POST',
                    headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
                    body: JSON.stringify(resource),
                });
                res.ok ? result.created++ : result.failed++;
            }
        } catch {
            result.failed++;
        }
    }

    return result;
}

/**
 * Write a single FHIR Appointment into OpenEMR's calendar (reverse sync: FHIR → OpenEMR)
 */
export interface FHIRAppointmentInput {
    fhirAppointmentId: string;
    patientName: string;
    practitionerName: string;
    start: string;       // ISO datetime
    end?: string;        // ISO datetime
    status: string;      // booked, cancelled, etc.
    serviceType?: string;
    description?: string;
}

const FHIR_STATUS_TO_OPENEMR: Record<string, string> = {
    booked: '-',
    arrived: '>',
    fulfilled: 'x',
    cancelled: '%',
    noshow: '?',
    proposed: '-',
};

/**
 * Find OpenEMR patient ID (pid) by name (best-effort match)
 */
async function resolvePatientPid(patientName: string): Promise<number> {
    if (!pool) return 0;
    const parts = patientName.trim().split(/\s+/);
    const lname = parts.pop() || '';
    const fname = parts.join(' ') || '';
    try {
        const [rows] = await pool.query(
            'SELECT pid FROM patient_data WHERE fname LIKE ? AND lname LIKE ? LIMIT 1',
            [`%${fname}%`, `%${lname}%`]
        ) as any;
        if (rows.length > 0) return rows[0].pid;
        // Fallback: search by last name only
        const [rows2] = await pool.query(
            'SELECT pid FROM patient_data WHERE lname LIKE ? LIMIT 1',
            [`%${lname}%`]
        ) as any;
        return rows2.length > 0 ? rows2[0].pid : 0;
    } catch { return 0; }
}

/**
 * Find OpenEMR user ID (aid) by practitioner name
 */
async function resolvePractitionerAid(practName: string): Promise<number> {
    if (!pool) return 0;
    const clean = practName.replace(/^Dr\.?\s*/i, '').trim();
    const parts = clean.split(/\s+/);
    const lname = parts.pop() || '';
    const fname = parts.join(' ') || '';
    try {
        // Try matching by fname + lname
        if (fname) {
            const [rows] = await pool.query(
                'SELECT id FROM users WHERE fname LIKE ? AND lname LIKE ? AND active = 1 LIMIT 1',
                [`%${fname}%`, `%${lname}%`]
            ) as any;
            if (rows.length > 0) return rows[0].id;
        }
        // Fallback: match by lname only
        const [rows2] = await pool.query(
            'SELECT id FROM users WHERE lname LIKE ? AND active = 1 LIMIT 1',
            [`%${lname}%`]
        ) as any;
        if (rows2.length > 0) return rows2[0].id;
        // Fallback: match by username containing the name
        const [rows3] = await pool.query(
            'SELECT id FROM users WHERE username LIKE ? AND active = 1 LIMIT 1',
            [`%${clean.toLowerCase().replace(/\s+/g, '')}%`]
        ) as any;
        return rows3.length > 0 ? rows3[0].id : 1; // default to admin (id=1)
    } catch { return 1; }
}

export async function writeAppointmentToOpenEMR(input: FHIRAppointmentInput): Promise<{ ok: boolean; eid?: number; error?: string }> {
    if (!pool) return { ok: false, error: 'OpenEMR DB pool not initialized' };

    try {
        const pid = await resolvePatientPid(input.patientName);
        const aid = await resolvePractitionerAid(input.practitionerName);

        // Parse local date/time from the ISO string to avoid UTC conversion issues
        // Input format: 2026-03-27T09:00:00+08:00
        const isoMatch = input.start.match(/^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2}:\d{2})/);
        const eventDate = isoMatch ? isoMatch[1] : new Date(input.start).toISOString().split('T')[0];
        const startTime = isoMatch ? isoMatch[2] : '09:00:00';

        let endTime = '09:30:00';
        if (input.end) {
            const endMatch = input.end.match(/T(\d{2}:\d{2}:\d{2})/);
            endTime = endMatch ? endMatch[1] : startTime;
        } else {
            // Default: start + 30 min
            const [h, m, s] = startTime.split(':').map(Number);
            const totalMin = h * 60 + m + 30;
            endTime = `${String(Math.floor(totalMin / 60)).padStart(2, '0')}:${String(totalMin % 60).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
        }

        const startDate = new Date(input.start);
        const endDate = input.end ? new Date(input.end) : new Date(startDate.getTime() + 30 * 60000);
        const duration = Math.round((endDate.getTime() - startDate.getTime()) / 1000); // in seconds
        const apptStatus = FHIR_STATUS_TO_OPENEMR[input.status] || '-';
        const title = input.serviceType || 'Office Visit';

        // Check if this FHIR appointment is already synced
        const [existing] = await pool.query(
            'SELECT pc_eid FROM openemr_postcalendar_events WHERE pc_hometext LIKE ? LIMIT 1',
            [`%fhir:${input.fhirAppointmentId}%`]
        ) as any;

        // Resolve provider's facility_id
        let facilityId = 3; // default
        try {
            const [facRows] = await pool.query('SELECT facility_id FROM users WHERE id = ? LIMIT 1', [aid]) as any;
            if (facRows.length > 0 && facRows[0].facility_id > 0) facilityId = facRows[0].facility_id;
        } catch {}

        if (existing.length > 0) {
            // Update existing (also fix facility)
            await pool.query(
                `UPDATE openemr_postcalendar_events SET pc_apptstatus = ?, pc_title = ?, pc_facility = ?, pc_hometext = ? WHERE pc_eid = ?`,
                [apptStatus, title, facilityId, `${input.description || ''}\n[fhir:${input.fhirAppointmentId}]`, existing[0].pc_eid]
            );
            console.log(`[OpenEMR-WriteBack] Updated appointment eid=${existing[0].pc_eid} for fhir:${input.fhirAppointmentId}`);
            return { ok: true, eid: existing[0].pc_eid };
        }

        // Insert new appointment into OpenEMR calendar
        const [result] = await pool.query(
            `INSERT INTO openemr_postcalendar_events
             (pc_catid, pc_aid, pc_pid, pc_title, pc_eventDate, pc_startTime, pc_endTime,
              pc_duration, pc_apptstatus, pc_eventstatus, pc_facility, pc_hometext,
              pc_recurrtype, pc_recurrspec, pc_recurrfreq, pc_informant,
              pc_sharing, pc_prefcatid, pc_billing_location)
             VALUES (5, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?, 0, '', 0, ?, 1, 0, ?)`,
            [aid, pid, title, eventDate, startTime, endTime, duration, apptStatus,
             facilityId, `${input.description || ''}\n[fhir:${input.fhirAppointmentId}]`, aid, facilityId]
        ) as any;

        const eid = result.insertId;
        console.log(`[OpenEMR-WriteBack] Created appointment eid=${eid} | pid=${pid} | aid=${aid} | ${eventDate} ${startTime}`);
        return { ok: true, eid };
    } catch (err: any) {
        console.error('[OpenEMR-WriteBack] Error:', err.message);
        return { ok: false, error: err.message };
    }
}
